# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Community Calendar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Community Calendar
  pod 'Auth0', '~> 1.19'
  pod "Apollo"
  
end
