# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Community Calendar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Comment the next line if you would like to see framework warnings
  inhibit_all_warnings!
  # Pods for Community Calendar
  pod 'Auth0', '~> 1.19'#, :inhibit_warnings => true # Uncomment to hide warnings from this specific framework
  pod "Apollo"#, :inhibit_warnings => true # Uncomment to hide warnings from this specific framework
  
end
